version: '3.8'

services:
  web:
    build: .
    user: "0:0"  # Run as root to access OpenVPN system files
    network_mode: "host"
    ports:
      - "8100:8100"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://localhost:6379/0  # localhost because of host networking
      - VPN_HOST=localhost
      - VPN_PORT=1194
      - VPN_PROTO=udp
      - VPN_CLIENT_DIR=/etc/openvpn/client
      - HOTSPOT_TEMPLATE_DIR=/var/www/templates
    depends_on:
      - redis
    volumes:
      - .:/app
      - /etc/openvpn:/etc/openvpn
      - /var/log/openvpn:/var/log/openvpn
      - /var/www/templates:/var/www/templates
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    networks:
      - app-network

  celery_worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    user: "0:0"
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://localhost:6379/0
      - VPN_HOST=localhost
      - VPN_PORT=1194
      - VPN_PROTO=udp
      - VPN_CLIENT_DIR=/etc/openvpn/client
      - HOTSPOT_TEMPLATE_DIR=/var/www/templates
    depends_on:
      - redis
      - web
    volumes:
      - .:/app
      - /etc/openvpn:/etc/openvpn
      - /var/log/openvpn:/var/log/openvpn
      - /var/www/templates:/var/www/templates
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
